### PR TITLE
Enhancement/Action tests

### LINKED ISSUE #290: Run the integration-tests on a more large pannel of python versions
In the `tests.yml` file we are currently running the tests on these python version 

- 3.8
- 3.9

Python `3.11` is out and it should be added in this matrix as well.  Should we keep running the tests on 3.8 and 3.9?

Additionally the tests should be added in the [`bors.toml`](https://github.com/meilisearch/docs-scraper/blob/main/bors.toml) file and the settings of the repo.

### PR DESCRIPTION
**Pull request by brunoocasali**
Fixes #290 

I think we can keep the last three minor releases of Python. This PR adds those last three minors to `unit_tests` and `integration_tests` actions.
The linter action runs only against the python version we have in the final docker image.

### CODE REVIEW

**Review by alallema — DISMISSED** [review]
Well Done @brunoocasali thank again to take care of this repo ❤️ 
LGTM!

**Comment by alallema** [comment]
bors merge

**Comment by brunoocasali** [comment]
bors merge

**Comment by alallema** [comment]
> Timed out.
Screenshot 2022-12-06 at 15 29 49
Weird! But at this point, I don't think it a coincidence no?

**Comment by bidoubiwa** [comment]
We could try to run the tests locally on a python 3.8 environment

**Comment by sanders41** [comment]
Python 3.8 was removed from the test matrix, but it's still required in the `bors.toml`

**Comment by brunoocasali** [comment]
> Python 3.8 was removed from the test matrix, but it's still required in the `bors.toml`. Also 3.10 and 3.11 are missing from bors with this new matrix.

well spotted @sanders41 thanks!

**Comment by alallema** [comment]
bors merge

**Pull request merged**
