### PR TITLE
Update README with links to new docs website

### PR DESCRIPTION
**Pull request by guimachiavelli**
We recently migrated the docs to a new website. Our new address is https://meilisearch.com/docs.

### CODE REVIEW

**Comment by sanders41** [comment]
Always fun when tests break on unrelated updates :upside_down_face: . The tests failed because [docs-basic.config.json](https://github.com/meilisearch/docs-scraper/blob/main/tests/config_files_examples/docs-basics.config.json) and [docs-custom.config.json](https://github.com/meilisearch/docs-scraper/blob/main/tests/config_files_examples/docs-custom.config.json) are both still pointing to the old docs site. 

Fixing the basic config should be easy, but the custom config is using https://docs.meilisearch.com/sitemap.xml. It looks like the `sitemap.xml` file doesn't exist any more under the new site?

**Comment by guimachiavelli** [comment]
Hi, @sanders41!

You're right, `sitemap.xml` does not currently exist. Is it mandatory for the correct functioning of the docs scraper, or is it possible to find a way around it? Pinging @bidoubiwa and @brunoocasali since you probably understand this setup better than me ❤️ 

I'm asking because there are quite a few things the website devs need to work on and we need to know what to prioritise.

**Comment by sanders41** [comment]
The `sitemap.xml` is not mandatory. @bidoubiwa / @brunoocasali  my assumption is the custom config is using the sitemap to test will work this way also?

**Comment by bidoubiwa** [comment]
It should still work, as you said, it is not mandatory. I think it helps scrapping faster? Anyway it should work.

Can you remove these lines from the docs-configs files mentioned by @sanders41

**Comment by brunoocasali** [comment]
Plus, @guimachiavelli do you know if the agency changed the overall structure in the scrapping code? Also, do you know if the scrapping is working since we have the same structure in production here: https://github.com/meilisearch/documentation/blob/a0ad491bc474bedc25ffaee509812c551a5e6168/docs-scraper.config.json#L7

In other words, if it breaks here, it will also break in the documentation CI.

**Comment by guimachiavelli** [comment]
@brunoocasali: no, I don't. 

@justkahdri, can you describe the changes we had to make so the scraper would work with the new docs site? Thanks!

**Comment by bidoubiwa** [comment]
Hey @guimachiavelli, 

You can remove this line: 
https://github.com/meilisearch/docs-scraper/blob/7942cdd394743cab3c1536f9260d2ceaed81d018/tests/config_files_examples/docs-custom.config.json#L3

And changes these lines with the new docs link:

https://github.com/meilisearch/docs-scraper/blob/7942cdd394743cab3c1536f9260d2ceaed81d018/tests/config_files_examples/docs-basics.config.json#L3
https://github.com/meilisearch/docs-scraper/blob/7942cdd394743cab3c1536f9260d2ceaed81d018/tests/config_files_examples/docs-custom.config.json#L4

**Review by alallema — APPROVED** [review]
Thanks, @guimachiavelli for this PR ❤️ 
Sorry for not taking care of it sooner 😊

**Comment by alallema** [comment]
bors merge

**Comment by guimachiavelli** [comment]
oh, thanks, @alallema! ❤️ 

I had this on my todo list, but didn't have much free time these past few weeks. Thanks again!

**Pull request merged**
