### PR TITLE
Fix asc/desc syntax: make it work for MeiliSearch v0.22.0 and later

### PR DESCRIPTION
**Pull request by curquiza**
Related to https://github.com/meilisearch/MeiliSearch/discussions/1766

### CODE REVIEW

**Comment by curquiza** [comment]
@bidoubiwa, docs-scraper does not currenlty work with MeiliSearch v0.22.0 and later, so we should merge it and release it asap :)

**Comment by curquiza** [comment]
I think this is breaking since we enforce the usage of v0.22.0 of MeiliSearch and later

**Review by bidoubiwa — APPROVED** [review]
My bad for not fixing this during the previous release. LGTM !

**Comment by bidoubiwa** [comment]
bors merge

**Comment by curquiza** [comment]
I totally missed it as well, don't worry! :)

**Pull request merged**
