### PR TITLE
Update pylint from 2.6.2 to 2.7.4  #114

### LINKED ISSUE #114: Upgrade pylint
Upgrade pylint (like in this PR https://github.com/meilisearch/docs-scraper/pull/113) and fix the linter errors.

### PR DESCRIPTION
**Pull request by AABur**
Fix #114

Linter errors are caused by duplicate code in tests.
I suggest parameterising the tests with @pytest.mark.parametrize and @pytest.fixtures. Then common fixtures can be put in conftest.py

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Hello @AABur 

I've looked at your suggestion and it is a good solution. Put every fixtures in the conftest file. 
But there is a small thing that makes me doubt that decision. I feel like we lose easy context on each test. We will have to go find the used fixture in a separate file to understand with which resources the tests is running.

Now the other argument is that if we want to change the tests tomorrow the fixtures will only have to be changed in `one` file.  But I think the cost of loosing context is higher than changing multiple tests fixtures.

Also, I think I understand pylint's rule in the context of source files as it would make the package heavier and would duplicate code. But i'm less convinced in the context of tests files.

I would like your opinion on this.

If you agree with me on the fact that we should not have this rule on the tests multiple solutions are possible: 

1. Ignore the duplicate rule only in the tests dir. See this [stackoverflow](https://stackoverflow.com/questions/47312047/disable-pylint-message-for-a-given-module-or-directory)
2. disable that linting rule globally by adding `disable=R0801` in the .pylintrc file
3. Lastly, we can add on every problematic line a comment [like this solution on the in the pylint issue of the matter](https://github.com/PyCQA/pylint/issues/214)
```python
    strategy.dom = lxml.html.fromstring("""
        <html><body>
         <h1>Foo</h1>
         <h2>Bar</h2>
         <h3>Baz</h3>
         <p>text</p>
        </body></html>
        """) # pylint: disable=duplicate-code

        actual = strategy.get_records_from_dom()
```

and that means adding the following rule in pylintrc: 
```
[SIMULARITIES]
ignore-comments = "no"
```

In case of more than 2 files, well
```python
# pylint: disable=duplicate-code_1
```

```python
# pylint: disable=duplicate-code_2
```

Here are some related issues: 
- https://github.com/PyCQA/pylint/issues/3239
- https://github.com/PyCQA/pylint/issues/214

Another solution that is suggested is increasing: 
```
# Changed to 10, previously 4
min-similarity-lines=10
```
In the pylint file.
But that does not seem to solve the issue and also is very hacky.

**Comment by AABur** [comment]
I understand your point about the possible loss of context. In my opinion, the rational use of fixtures would not create a problem in this regard. On the other hand, fixtures will help simplify code understanding and support in the future. 

First of all, we are not forced to keep fixtures into one separate file. We can keep them for each test file individually.
Second, context-sensitive naming of fixtures also helps preserve context.

**For example**, the following code appears in 9 files 17 times without any changes and 15 times with one of the keys' values changes (I hope I didn't count too wrong)

```
	  'selectors': {
	      "lvl0": "h1",
	      "lvl1": "h2",
	      "lvl2": "h3",
	      "content": "p"
	  },
```

In this case, it is worthwhile to use a fixture. 
```
	  @pytest.fixture
	  def standard_selectors():
	      return {
	          "lvl0": "h1",
	          "lvl1": "h2",
	          "lvl2": "h3",
	          "content": "p"
	      }
```
and use it in the code as follows

```
	  def test_default_page_rank_should_be_zero(self, standard_selectors):
		        # Given
		        strategy = get_strategy({
		            'selectors': standard_selectors
		        })
		    ...
```

Pros:
1. Simple and straightforward code
2. To change the standard selectors, just fix the code in one place.

Cons:
1. To find out the value of standard selectors, you need to view them in a separate file.

**And one more example** https://github.com/meilisearch/docs-scraper/blob/main/scraper/src/tests/default_strategy/tags_test.py
There are three tests in this module, similar at first glance but not the same as they seem. This is caused by the way the code is written.

In fact, the difference between these tests is minimal:
- first vs second: 
first:
`actual = strategy.get_records_from_dom("http://foo.bar/api")`
second:
`actual = strategy.get_records_from_dom("http://foo.bar/api/test")`

- first vs third:

first:
```
'start_urls': [{
	'url': 'http://foo.bar/api',
	'tags': ["test"]
}],
...
actual = strategy.get_records_from_dom("http://foo.bar/api")
...
```
second:
```
'start_urls': [{
	'url': 'http://foo.bar/.*',
	'tags': ["test"]
}],
...
actual = strategy.get_records_from_dom("http://foo.bar/api")
...
```

- second vs third:
second:
```
'start_urls': [{
	'url': 'http://foo.bar/.*',
	'tags': ["test"]
}],
```
third:
```
'start_urls': [{
	'url': 'http://foo.bar/api',
	'tags': ["test"]
}],
```
Using `@pytest.mark.parametrize` can greatly simplify the code https://gist.github.com/ee8206c492d0c5d92d52c595d0e42923
In my opinion, the context is not lost here

**As a result, my suggestion is not to abandon parametrized tests where it makes sense to do so.**

**Comment by bidoubiwa** [comment]
Thanks so much for this in-depth explanation! I agree with your solution :fire: Is it okay for you to implement it?

**Comment by AABur** [comment]
Of course, I am ready to implement it! 🦾
Already started 👨‍💻

**Comment by bidoubiwa** [comment]
Hello @AABur, are you still on this PR? If not, no problem, I can take it from here :)

**Comment by AABur** [comment]
Hi @bidoubiwa!
I've been busy with other projects. They are now finished (or at least not too time-consuming). I want to get back to this task if it is still relevant.
Thank you for the reminder.

**Comment by bidoubiwa** [comment]
It is still relevant :) Thanks so much

**Comment by AABur** [comment]
This PR is obsolete and I think it should be closed. And so is the relevant issue #114.

**Pull request closed without merging**
