### PR TITLE
Add back chromedriver tests

### LINKED ISSUE #177: Fix chromedrivers tests in CI that had to be removed
**Description**
The tests on the chromedriver are [removed again](https://github.com/meilisearch/docs-scraper/pull/173) from the CI because of failing tests with selenium

[See failing tests](https://github.com/meilisearch/docs-scraper/runs/4056190321?check_suite_focus=true)

> run: pipenv run pytest -m "not chromedriver"

**Expected behavior**
Not fail

**Current behavior**
```
=========================== short test summary info ============================
FAILED tests/config_loader/open_selenium_browser_test.py::TestOpenSeleniumBrowser::test_browser_needed_when_config_contains_automatic_tag
```

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

### PR DESCRIPTION
**Pull request by sanders41**
# Pull Request

@alallema I saw the publish to docker hub failed. I think the version check script should point to the version file for `docs-scraper` and not `meilisearch-python`?

## Related issue
Fixes #177

## What does this PR do?
- Adds the chromedriver tests back to CI

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by sanders41** [comment]
Alright, what I think I have here is an improvement, but it still needs work. I have all the `chromedriver` tests working except for `test_browser_needed_when_config_contains_automatic_tag`. For this one I think the issue is it is trying to use `jquery`, but `jquery` isn't available. While we try to come up with a solution for this I have set that test to `xfail` (expected to fail).

I still think in the long run it would be better to mock, or use the docs site like you said, but at least this get some `chromedriver` tests going for now.

**Comment by alallema** [comment]
Perfect is good enough for me.
On the other hand, I don't like the solution with `xfail` since this test shouldn't fail, just the test is broken. I'd suggest instead, and if you agree or remove completely this test or comment it, write an issue about it and add the link to the comment on the test. (I can write the issue of course) WDYT?

**Comment by sanders41** [comment]
I wouldn't worry about the `xfail`, this is the situation that pytest made it for. It is actually helpful in a lot of situations. Because it is set to `strict`, if it starts passing for some reason the test will fail and we will know the problem is fixed and the `xfail` can be removed. It also makes it clear that this test needs work and we know it is going to fail right now.
If you are interested Paul Gannsel (a Python core developer) has a blog post about this https://blog.ganssle.io/articles/2021/11/pytest-xfail.html

With that said, if you would still rather comment out the test we can.

**Comment by alallema** [comment]
> this is the situation that pytest made it for

I didn't know that. Thank you for the explanation.

**Review by alallema — APPROVED** [review]
LGTM! 🚀

**Comment by alallema** [comment]
bors merge

**Pull request merged**
